export default (ar = {
  home: 'الرئيسية',
  mobile: 'رقم الجوال',
  password: 'الرقم السرى',
  login: 'دخول',
  english: 'English',
  arabic: 'العربية',
  proceed: 'التالى',
  complete: 'تم',
  thereIsError: 'يوجد خطأ',
  pleaseFill: 'يرجى ملء الحقول',
  cancel: 'إلغاء',
  yes: 'نعم',
  doneMessage: 'تمت العملية بنجاح',
  back: 'رجوع',
  changeLang: 'تغيير اللغة',
  noInternetConnection: 'لا يوجد إتصال بالإنترنت',
  anErrorOccured: 'حدث خطأ',
  edit: 'تعديل',
  delete: 'حذف',
  addPost: 'أضف منشورا',
  title: 'العنوان',
});
