export default (en = {
  home: 'Home',
  english: 'English',
  arabic: 'العربية',
  proceed: 'Proceed',
  complete: 'Done',
  thereIsError: 'There is error',
  cancel: 'Cancel',
  yes: 'Yes',
  doneMessage: 'Process is done successfully',
  back: 'Back',
  changeLang: 'Change language',
  about: 'About us',
  noInternetConnection: 'No internet connection',
  anErrorOccured: 'an Error Occured',
  edit: 'Edit',
  delete: 'Delete',
  addPost: 'add Post',
  title: 'Title',
});
